$pdflatex = "pdflatex %O -interaction nonstopmode %S";
$go_mode = 1;
$out_dir = "out";
$aux_dir = "aux";
$pdf_mode = 1; $postscript_mode = $dvi_mode = 0;
$ENV{'TEXINPUTS'}      	= "../:" . ($ENV{'TEXINPUTS'} // "");
$ENV{'max_print_line'} 	= 1000; # Cualquier numero
$ENV{'error_line'}     	= 254; # Maximo: 254
$ENV{'half_error_line'}	= 238; # Maximo: error_line - 16